apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-file
  template:
    metadata:
      labels:
        app: upload-file
    spec:
      volumes:
        - name: upload-file-storage
          persistentVolumeClaim:
            claimName: upload-file-pv-claim
      containers:
      - name: server
        image: upload-file
        volumeMounts:
          - name: upload-file-storage
            mountPath: /uploaded_files
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y

