apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-file-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/heri/Work/CODES/LAB/KubePersistenceVolume"